// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFsGtN882FB-n6w6T2xv-wRtwFic7d8n8',
    appId: '1:5155552973:web:c48188c79dad085efd7384',
    messagingSenderId: '5155552973',
    projectId: 'lmss-5a470',
    authDomain: 'lmss-5a470.firebaseapp.com',
    storageBucket: 'lmss-5a470.firebasestorage.app',
    measurementId: 'G-7HPP9WGT15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8dTNTEtWVf-S2eZm10RWPbfznLOsZZe8',
    appId: '1:5155552973:android:6bd343d7a2e9d021fd7384',
    messagingSenderId: '5155552973',
    projectId: 'lmss-5a470',
    storageBucket: 'lmss-5a470.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOnoYyNExqtrtrhR508vdLiZNl0wjJEyQ',
    appId: '1:5155552973:ios:47d31f67adc2dcbafd7384',
    messagingSenderId: '5155552973',
    projectId: 'lmss-5a470',
    storageBucket: 'lmss-5a470.firebasestorage.app',
    iosClientId: '5155552973-08r0tsciob53k5dm04mm98nrcp4bjois.apps.googleusercontent.com',
    iosBundleId: 'com.example.lms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOnoYyNExqtrtrhR508vdLiZNl0wjJEyQ',
    appId: '1:5155552973:ios:47d31f67adc2dcbafd7384',
    messagingSenderId: '5155552973',
    projectId: 'lmss-5a470',
    storageBucket: 'lmss-5a470.firebasestorage.app',
    iosClientId: '5155552973-08r0tsciob53k5dm04mm98nrcp4bjois.apps.googleusercontent.com',
    iosBundleId: 'com.example.lms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFsGtN882FB-n6w6T2xv-wRtwFic7d8n8',
    appId: '1:5155552973:web:c8b09d8b15c70b0ffd7384',
    messagingSenderId: '5155552973',
    projectId: 'lmss-5a470',
    authDomain: 'lmss-5a470.firebaseapp.com',
    storageBucket: 'lmss-5a470.firebasestorage.app',
    measurementId: 'G-DMB59E10Q0',
  );
}